### PR TITLE
I created article.html(file) to create article page

### PR DESCRIPTION
**Pull request by MaximeLeBerre**

### CODE REVIEW

**Review by Aurelien-Lamarre — CHANGES_REQUESTED** [review]
Nice job just you unlinked the js page.

**Review by Rooarii — CHANGES_REQUESTED** [review]
good job, can you remove wrap class of main tag and use color defined in root.

**Comment by MaximeLeBerre** [comment]
requested changes added !

**Review by Rooarii — APPROVED** [review]

**Review by Aurelien-Lamarre — APPROVED** [review]
Nice.

**Review by samson-corbiere — APPROVED** [review]

**Pull request merged**
